---
ignore:
  # Mitigated by 'omniauth-rails_csrf_protection' gem
  - CVE-2015-9284

  # Waiting on Rails 6.1+ upgrade
  - GHSA-p84v-45xj-wwqj
  - GHSA-8xww-x3g3-6jcv
  - GHSA-579w-22j4-4749
  - GHSA-j6gc-792m-qgm2
  - CVE-2023-28120
  - GHSA-4g8v-vg43-wpgf
  - GHSA-xp5h-f8jf-rc8q
  - GHSA-8h22-8cf7-hq6g
  - GHSA-cr5q-6q9f-rq6q
