---
ignore:
  # Mitigated by 'omniauth-rails_csrf_protection' gem
  - CVE-2015-9284

  # Waiting on Rails 6.1+ upgrade
  - GHSA-h47h-mwp9-c6q6
  - GHSA-p84v-45xj-wwqj
  - GHSA-8xww-x3g3-6jcv
  - GHSA-4g8v-vg43-wpgf
  - GHSA-x76w-6vjr-8xgj
  - GHSA-vfg9-r3fq-jvx4
  - GHSA-vfm5-rmrh-j26v
  - GHSA-wwhv-wxv9-rpgw
  - GHSA-xp5h-f8jf-rc8q
  - GHSA-579w-22j4-4749
  - GHSA-76r7-hhxj-r776
  - GHSA-8h22-8cf7-hq6g
  - GHSA-r4mg-4433-c7g3
  - GHSA-j6gc-792m-qgm2
  - GHSA-pj73-v5mw-pm9j
  - GHSA-cr5q-6q9f-rq6q
