dist: bionic

language: ruby
cache: bundler
bundler_args: --without development --jobs 4
sudo: false

services:
  - mysql
  - postgresql

addons:
  chrome: stable
  apt:
    packages:
      - imagemagick
      - ghostscript

env:
  - DB=postgresql
  - DB=mysql

rvm:
  - 2.5.8
  - 2.6.6
  - 2.7.2

before_install:
  - gem install bundler -v 1.17.3

before_script:
  - psql -c 'CREATE DATABASE brimir_test;' -U postgres
  - mysql -e 'create database brimir_test;'
  - cp config/database.travis.yml config/database.yml
  - bundle exec rake db:migrate
  - bundle exec rails runner -e test 'Webdrivers.install_dir = Rails.root.join("vendor", "webdrivers"); Webdrivers::Chromedriver.update'
