os:
  - linux
dist: bionic

language: ruby
rvm:
  - 2.5.7
  - 2.6.5

cache:
  bundler: true
  yarn: true
  directories:
    - node_modules

bundler_args: --without development --jobs 4

addons:
  chrome: stable
  apt:
    packages:
      - imagemagick
      - ghostscript

services:
  - postgresql
  - mysql

env:
  - DB=postgresql
  - DB=mysql

before_install:
  - yes | gem update --system --force
  - gem install bundler
  - yarn install

before_script:
  - psql -c 'CREATE DATABASE brimir_test;' -U postgres
  - mysql -e 'CREATE DATABASE IF NOT EXISTS brimir_test;'
  - cp config/database.travis.yml config/database.yml
  - bundle exec rake db:migrate
