language: ruby
cache: bundler
bundler_args: --without development --jobs 4
sudo: false

addons:
  apt:
    packages:
      - imagemagick
      - ghostscript

env:
  - DB=postgresql
  - DB=mysql

rvm:
  - 2.4.6
  - 2.5.5
  - 2.6.3

before_install:
  - gem update --system
  - gem install bundler

before_script:
  - psql -c 'CREATE DATABASE brimir_test;' -U postgres
  - mysql -e 'create database brimir_test;'
  - cp config/database.travis.yml config/database.yml
  - bundle exec rake db:migrate
